### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'at') 

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/branch-diff#71]
While preparing Node v20.16.0 release:
```
marcoippolito@marcos-MacBook-Pro node % N=20 sh -c 'branch-diff v$N.x-staging v22.4.0 --exclude-label=semver-major,dont-land-on-v$N.x,backport-requested-v$N.x,backport-blocked-v$N.x,backport-open-v$N.x,backported-to-v$N.x,baking-for-lts --filter-release --format=simple'
TypeError: Cannot read properties of undefined (reading 'at')
    at normalizeIfTrailingSlash (file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:57:20)
    at isInList (file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:64:5)
    at file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:83:51
    at Array.filter (<anonymous>)
    at diffCollected (file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:83:31)
    at branchDiff (file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:47:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///Users/marcoippolito/.nvm/versions/node/v20.15.0/lib/node_modules/branch-diff/branch-diff.js:173:14)
```

**Comment by rvagg** [comment]
https://github.com/nodejs/branch-diff/blob/85790dc20ae63761b6862a500803bf79a09595f3/branch-diff.js#L57

https://github.com/nodejs/branch-diff/pull/70 should have checked first whether `prUrl` even exists

@RafaelGSS pls take a look

**Comment by RafaelGSS** [comment]
> https://github.com/nodejs/branch-diff/blob/85790dc20ae63761b6862a500803bf79a09595f3/branch-diff.js#L57
> 
> 
> 
> https://github.com/nodejs/branch-diff/pull/70 should have checked first whether `prUrl` even exists
> 
> 
> 
> @RafaelGSS pls take a look

I'm not with my computer right now. I should be able to fix it in a couple hours. Sorry about that

**Comment by marco-ippolito** [comment]
fixed by https://github.com/nodejs/branch-diff/pull/72
